#' A Custom ggplot2 Theme for NMFprofileR Visuals
#'
#' This internal helper function provides a consistent and clean ggplot2 theme
#' for plots generated by the NMFprofileR package.
#'
#' @return A ggplot2 theme object.
#' @noRd
custom_theme <- function() {
  ggplot2::theme(
    legend.position = "right",
    panel.background = ggplot2::element_rect(fill = "#f2f2f2", colour = "#f2f2f2"),
    panel.grid.major = ggplot2::element_line(size = 0.5, linetype = 'solid', colour = "#dbe3db"),
    panel.grid.minor = ggplot2::element_line(size = 0.25, linetype = 'solid', colour = "#dbe3db"),
    axis.title = ggplot2::element_text(size = 14),
    axis.text = ggplot2::element_text(size = 12),
    panel.border = ggplot2::element_rect(colour = "black", fill = NA, size = 0.5)
  )
}


#' Generate All Plots for a Single NMF Rank
#'
#' This internal function creates a comprehensive suite of visualizations for the
#' results of a single NMF run (for a specific rank k). It saves all plots as
#' PDF files in a rank-specific directory.
#'
#' @param k The current rank (integer).
#' @param nmf_result The NMFfit object from the `NMF` package.
#' @param sample_assignments A data frame mapping samples to their dominant factor.
#' @param combined_gprofiler_df A data frame of all PER-FACTOR enrichment results.
#' @param combined_enrichment_results_df A data frame from the analysis of ALL basis genes.
#' @param expr_matrix The original, filtered expression matrix.
#' @param basis_genes A list of basis genes for each factor.
#' @param k_plots_dir The path to the output directory for this rank's plots.
#' @param file_prefix The base prefix for all output file names.
#' @param nrun The number of NMF runs performed.
#' @param top_n The number of top enriched terms to display in dot plots.
#'
#' #' @importFrom tidyselect where
#'
#' @noRd
generate_rank_plots <- function(k, nmf_result, sample_assignments, combined_gprofiler_df,
                                combined_enrichment_results_df, expr_matrix, basis_genes,
                                k_plots_dir, file_prefix, nrun, top_n) {

  cli::cli_alert_info("Generating plots for k={k}...")

  # --- Create Annotation Objects for Heatmaps with a Robust Color Palette ---
  H <- NMF::coef(nmf_result)
  sample_annot_df <- data.frame(Factor = sample_assignments$Dominant_Factor)
  rownames(sample_annot_df) <- sample_assignments$SampleID

  # Define a base palette and extend it if k is large
  base_palette <- c("#008000", "#800080", "#ffcc00", "#d40000", "#d40055", "#0073c2")
  final_palette <- if (k <= length(base_palette)) {
    base_palette[1:k]
  } else {
    c(base_palette, grDevices::hcl.colors(k - length(base_palette), "viridis"))
  }
  factor_colors <- stats::setNames(final_palette, paste0("Factor_", 1:k))

  ha_col <- ComplexHeatmap::HeatmapAnnotation(
    df = sample_annot_df, col = list(Factor = factor_colors), which = "column",
    show_legend = TRUE, show_annotation_name = TRUE,
    annotation_name_gp = grid::gpar(fontsize = 8),
    annotation_legend_param = list(Factor = list(title = "NMF Factor"))
  )

  # --- Factor Summary Bar Plot ---
  factor_summary_df <- sample_assignments %>%
    dplyr::count(.data$Dominant_Factor, .drop = FALSE) %>%
    dplyr::mutate(Percent = (.data$n / sum(.data$n)) * 100)

  suppressWarnings({
    factor_summary_plot <- ggplot2::ggplot(factor_summary_df, ggplot2::aes(x = .data$Dominant_Factor, y = .data$Percent, fill = .data$Dominant_Factor)) +
      ggplot2::geom_col() +
      ggplot2::geom_text(data = . %>% dplyr::filter(.data$n > 0), ggplot2::aes(label = .data$n), vjust = -0.5) +
      ggplot2::labs(title = "NMF Factor Summary", subtitle = paste("k =", k), x = "NMF Factor", y = "Percent of Cohort") +
      ggplot2::theme_classic(base_size = 12) +
      ggplot2::scale_fill_manual(values = factor_colors, guide = "none", drop = FALSE) +
      custom_theme() +
      ggplot2::theme(legend.position = "none")

    ggplot2::ggsave(
      filename = file.path(k_plots_dir, paste0("02_Factor_Summary_Plot_Rank_k", k, ".pdf")),
      plot = factor_summary_plot, width = 6, height = 5, device = "pdf"
    )
  })
  # --- Enrichment Plots ---
  enrichment_plots_dir <- file.path(k_plots_dir, "Enrichment_Plots")
  dir.create(enrichment_plots_dir, showWarnings = FALSE, recursive = TRUE)

  # Plot 1: Dot Plot of Combined Enrichment Analysis (All Basis Genes)
  if (nrow(combined_enrichment_results_df) > 0) {
    plot_data_combined <- combined_enrichment_results_df %>%
      dplyr::slice_min(.data$p_value, n = top_n, with_ties = FALSE)

    suppressWarnings({
      combined_enrich_plot <- ggplot2::ggplot(plot_data_combined, ggplot2::aes(x = -log10(.data$p_value), y = forcats::fct_reorder(stringr::str_wrap(.data$term_name, 60), -log10(.data$p_value)))) +
        ggplot2::geom_segment(ggplot2::aes(x = 0, xend = -log10(.data$p_value), yend = forcats::fct_reorder(stringr::str_wrap(.data$term_name, 60), -log10(.data$p_value))), color = "gray") +
        ggplot2::geom_point(ggplot2::aes(size = .data$intersection_size), color = "purple4") +
        ggplot2::labs(title = "Top Enriched Terms from All Basis Genes", subtitle = paste("k =", k), x = "-Log10(Adjusted P-value)", y = NULL, size = "Gene Count") +
        ggplot2::theme_bw(base_size = 11) + custom_theme()

      plot_height_combined <- 4 + (nrow(plot_data_combined) * 0.25)
      ggplot2::ggsave(
        filename = file.path(enrichment_plots_dir, paste0("Enrichment_Dotplot_All_Factors_Combined_Rank_k", k, ".pdf")),
        plot = combined_enrich_plot, width = 10, height = plot_height_combined, device = "pdf", limitsize = FALSE
      )
    })
  }

  # Plot 2: Per-Factor and Per-Source Enrichment Dot Plots
  if (nrow(combined_gprofiler_df) > 0) {
    # Split data by source and factor to generate plots for each combination
    plot_groups <- split(combined_gprofiler_df, list(combined_gprofiler_df$source, combined_gprofiler_df$Factor))
    for (group_df in plot_groups) {
      if (nrow(group_df) > 0) {
        plot_data_enrich <- group_df %>% dplyr::slice_min(.data$p_value, n = top_n, with_ties = FALSE)
        src <- plot_data_enrich$source[1]
        factor_name <- plot_data_enrich$Factor[1]

        plot_height <- 3 + (nrow(plot_data_enrich) * 0.3)
        suppressWarnings({
          enrich_plot <- ggplot2::ggplot(plot_data_enrich, ggplot2::aes(x = -log10(.data$p_value), y = forcats::fct_reorder(stringr::str_wrap(.data$term_name, 60), -log10(.data$p_value)))) +
            ggplot2::geom_segment(ggplot2::aes(x = 0, xend = -log10(.data$p_value), yend = forcats::fct_reorder(stringr::str_wrap(.data$term_name, 60), -log10(.data$p_value))), color = "gray") +
            ggplot2::geom_point(ggplot2::aes(size = .data$intersection_size), color = "steelblue") +
            ggplot2::labs(title = paste("Top Enriched Terms:", src), subtitle = paste("Cohort k =", k, "|", factor_name), x = "-Log10(Adjusted P-value)", y = NULL, size = "Gene Count") +
            ggplot2::theme_bw(base_size = 11) + custom_theme() + ggplot2::theme(axis.text.y = ggplot2::element_text(size = 9))

          ggplot2::ggsave(
            filename = file.path(enrichment_plots_dir, paste0("Enrichment_Dotplot_Rank_k", k, "_", factor_name, "_", gsub(":", "_", src), ".pdf")),
            plot = enrich_plot, width = 8, height = plot_height, device = "pdf", limitsize = FALSE
          )
        })
      }
    }
  }

  # --- UMAP of Sample Coefficients ---
  H_matrix_t <- t(H)
  if (nrow(H_matrix_t) > 15) { # UMAP is more stable with >15 neighbors
    umap_res <- uwot::umap(H_matrix_t, n_neighbors = 15)
    umap_df <- as.data.frame(umap_res) %>%
      `colnames<-`(c("UMAP1", "UMAP2")) %>%
      dplyr::mutate(Dominant_Factor = sample_assignments$Dominant_Factor)

    suppressWarnings({
      umap_plot <- ggplot2::ggplot(umap_df, ggplot2::aes(x = .data$UMAP1, y = .data$UMAP2, color = .data$Dominant_Factor)) +
        ggplot2::geom_point(alpha = 0.8, size = 2) +
        ggplot2::scale_color_manual(values = factor_colors, drop = FALSE) +
        ggplot2::labs(title = "UMAP of NMF Sample Coefficients", subtitle = paste("k =", k), color = "NMF Factor") +
        ggplot2::theme_minimal() + custom_theme()

      ggplot2::ggsave(
        filename = file.path(k_plots_dir, paste0("05_UMAP_Plot_Rank_k", k, ".pdf")),
        plot = umap_plot, width = 7, height = 5.5, device = "pdf"
      )
    })
  }

  # --- Expression Heatmaps ---
  heatmap_plots_dir <- file.path(k_plots_dir, "Expression_Heatmaps")
  dir.create(heatmap_plots_dir, showWarnings = FALSE, recursive = TRUE)

  # Global Heatmap (all basis genes)
  genes_for_heatmap <- unique(unlist(basis_genes))
  if (length(genes_for_heatmap) > 0) {
    mat_plot <- expr_matrix[genes_for_heatmap, , drop = FALSE]
    mat_scaled <- t(scale(t(log2(mat_plot + 1))))
    mat_scaled[is.na(mat_scaled)] <- 0
    mat_scaled[mat_scaled > 2.5] <- 2.5
    mat_scaled[mat_scaled < -2.5] <- -2.5

    ht <- ComplexHeatmap::Heatmap(mat_scaled, name = "Row Z-Score",
                                  col = circlize::colorRamp2(c(-2.5, 0, 2.5), c("#3771c8", "white", "#ff9955")),
                                  top_annotation = ha_col, show_row_names = FALSE, show_column_names = FALSE,
                                  row_split = NMF::predict(nmf_result, what = "features")[genes_for_heatmap],
                                  column_split = NMF::predict(nmf_result, what = "samples"), use_raster = TRUE)

    grDevices::pdf(file.path(heatmap_plots_dir, paste0("Expression_Heatmap_Global_Rank_k", k, ".pdf")), 8, 7)
    ComplexHeatmap::draw(ht)
    grDevices::dev.off()
  }

  # --- NMF Diagnostic Plots ---
  if (nrun > 1) {
    # Capture and save Consensus Map
    cm_plot <- capture_plot({
      NMF::consensusmap(nmf_result, main = paste("Consensus Map: k =", k))
    })

    pdf(file.path(k_plots_dir, paste0("01_ConsensusMap_Rank_k", k, ".pdf")), 8, 8)
    replayPlot(cm_plot)
    dev.off()
  } else {
    cli::cli_alert_warning("Skipping Consensus Map (requires nmf_nrun > 1).")
  }

  # Capture and save Basis Map
  bm_plot <- capture_plot({
    NMF::basismap(nmf_result)
  })
  pdf(file.path(k_plots_dir, paste0("03_BasisMap_Rank_k", k, ".pdf")), 7, 9)
  replayPlot(bm_plot)
  dev.off()

  # Capture and save Coefficient Map
  cf_plot <- capture_plot({
    NMF::coefmap(nmf_result)
  })
  pdf(file.path(k_plots_dir, paste0("04_CoefMap_Rank_k", k, ".pdf")), 10, 8)
  replayPlot(cf_plot)
  dev.off()
}


#' Generate All Global Summary Plots for a Multi-Rank NMF Analysis
#'
#' Creates summary visualizations to compare results across all tested ranks.
#'
#' @param rank_metrics A data frame of quality metrics from `nmfEstimateRank`.
#' @param consolidated_summary_df A data frame summarizing all factors across ranks.
#' @param nmf_rank Integer vector of ranks that were tested.
#' @param nrun Number of NMF runs performed.
#' @param dirs A named list of output directories.
#' @param file_prefix The base prefix for output file names.
#' @importFrom tidyselect where
#'
#' @noRd
generate_global_plots <- function(rank_metrics, consolidated_summary_df, nmf_rank, nrun, dirs, file_prefix) {

  cli::cli_h2("Generating final summary files and global plots...")

  # --- Plot 1: Consolidated Summary Heatmap ---
  if (nrow(consolidated_summary_df) > 0) {
    summary_matrix <- consolidated_summary_df %>%
      dplyr::mutate(ID = paste0("k", .data$Rank, "_", .data$Factor)) %>%
      dplyr::select(-"Rank", -"Factor") %>%
      tibble::column_to_rownames("ID") %>%
      dplyr::select(where(is.numeric)) %>%
      as.matrix()

    # Scale and handle NA/Inf issues
    summary_matrix_scaled <- scale(summary_matrix, center = TRUE, scale = TRUE)
    summary_matrix_scaled[!is.finite(summary_matrix_scaled)] <- 0 # Replace NaN/Inf with 0

    if (nrow(summary_matrix_scaled) > 1 && ncol(summary_matrix_scaled) > 1) {
      ht_summary <- ComplexHeatmap::Heatmap(
        summary_matrix_scaled, name = "Scaled Value\n(Column Z-Score)",
        column_title = "Factor Summary Metrics Across All Ranks",
        row_split = consolidated_summary_df$Rank, row_title = "Rank k=%s",
        cluster_rows = TRUE, cluster_columns = TRUE
      )
      cli::cli_alert_info("Generating {.path 04_Consolidated_Summary_Heatmap.pdf}")
      grDevices::pdf(file.path(dirs$plots, "04_Consolidated_Summary_Heatmap.pdf"), 10, 8)
      ComplexHeatmap::draw(ht_summary)
      grDevices::dev.off()
    }
  }

  # --- Global plots below are only meaningful if >1 rank was tested ---
  if (length(nmf_rank) > 1) {
    # --- Plot 2: Factor Correspondence Heatmap ---
    all_basis_matrices <- lapply(nmf_rank, function(k_val) {
      nmf_obj_path <- file.path(dirs$nmf_core, paste0("NMF_Result_Object_Rank_k", k_val, ".rds"))
      if (file.exists(nmf_obj_path)) {
        mat <- NMF::basis(readRDS(nmf_obj_path))
        colnames(mat) <- paste0("k", k_val, "_F", 1:k_val)
        return(mat)
      }
      return(NULL)
    })
    all_basis_matrices <- all_basis_matrices[!sapply(all_basis_matrices, is.null)]

    if (length(all_basis_matrices) > 1) {
      # Align genes before combining matrices
      all_genes <- unique(unlist(lapply(all_basis_matrices, rownames)))
      aligned_matrices <- lapply(all_basis_matrices, function(m) {
        m_aligned <- matrix(0, nrow = length(all_genes), ncol = ncol(m), dimnames = list(all_genes, colnames(m)))
        m_aligned[rownames(m), ] <- m
        m_aligned
      })
      combined_basis_matrix <- do.call(cbind, aligned_matrices)
      cor_matrix <- stats::cor(combined_basis_matrix)
      annot_df <- data.frame(Rank = stringr::str_extract(colnames(cor_matrix), "k[0-9]+"))
      rownames(annot_df) <- colnames(cor_matrix)

      cli::cli_alert_info("Generating {.path 03_Factor_Correspondence_Heatmap.pdf}")
      grDevices::pdf(file.path(dirs$plots, "03_Factor_Correspondence_Heatmap.pdf"), 10, 9)
      pheatmap::pheatmap(cor_matrix, annotation_col = annot_df, annotation_row = annot_df,
                         main = "Factor Correspondence Across Ranks")
      grDevices::dev.off()
    }

    # --- Plot 3: Combined Consensus Maps ---
    if (nrun > 1) {
      nmf_list <- lapply(nmf_rank, function(k_val) {
        nmf_obj_path <- file.path(dirs$nmf_core, paste0("NMF_Result_Object_Rank_k", k_val, ".rds"))
        if (file.exists(nmf_obj_path)) readRDS(nmf_obj_path) else NULL
      })
      nmf_list <- nmf_list[!sapply(nmf_list, is.null)]

      if (length(nmf_list) > 0) {
        cli::cli_alert_info("Generating {.path 01_Combined_Consensus_Map.pdf}")
        n_plots <- length(nmf_list)
        n_cols <- min(n_plots, 3)
        n_rows <- ceiling(n_plots / n_cols)
        pdf_width <- 5 * n_cols
        pdf_height <- 4 * n_rows

        # Capture the combined consensus map plot
        cm_plot <- capture_plot({
          NMF::consensusmap(nmf_list, labCol = NA, labRow = NA)
        })

        pdf(file.path(dirs$plots, "01_Combined_Consensus_Map.pdf"),width = pdf_width, height = pdf_height)
        replayPlot(cm_plot)
        dev.off()

      }
    }
  }
}
